### ISSUE TITLE
CSS variable fallback values

### ISSUE THREAD

**Issue by subpx** [sveltekit/ui#3]
Are the fallback values for browser support? I don't think this approach really works.
If using components with your own css variables, you are unable to change the fallback value.
This means that the supporting and non-supporting browsers will style the components differently.

I think browser support is best handled by the user, if they require it.

I'm proposing to remove all the fallback values. Also defining a components css vars within its own style block:

`html {
    --Button-default-type-color: var(--green_4);
    --Button-rounded-border-radius:  50px;
  }`

The user could then globally override these values:

`:root {
    --Button-default-type-color: red;
    --Button-rounded-border-radius:  120px;
  }`

or use a more specific css selector for overriding these values:

`.specialButton {
    --Button-default-type-color: gold;
    --Button-rounded-border-radius:  50%;
  }`

**Comment by rob-balfre** [comment]
Hey stranger!

I was just copying what I did on svelte-select.  Basically having a default theme that you can override.  PostCSS handles IE11 if you need to support that.

Am I missing the point?

Our internal components have diverged a bit while we rush out a new project (nothing changes lol) so will hopefully get time to merge those changes into svelte-kit and decide on best approach with CSS custom props.  It's getting offical Svelte support soon I think so might hold off (https://github.com/sveltejs/rfcs/pull/13)

**Comment by subpx** [comment]
Howdy.

Yeah that makes sense. I was a bit confused with how that worked.
Custom CSS props sounds awesome! Get that into a branch when you can.

Im currently working on a custom theme for the components in an app Im building.
So I will be a good use case.

One thing I noticed already is buttons are the WORST for theming.
Soooo many css props. Basically everything needs a css var.

eg:

default button bg
default button text
default button hover bg
default button hover text
default button active bg

You get the point. Ill try do a PR, once ive at least got buttons working for me.
